import { ReactNode } from 'react';
import Background from '../app/Components/Background';

export const metadata = {
  title: 'Pritam Nayak Couture',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body style={{
        margin: 0,
        padding: 0,
        minHeight: '100vh',
        width: '100vw',
        height: '100%',
        overflow: 'hidden',
        display: 'flex',
        flexDirection: 'column',
      }}>
        <Background />
      
     
          {children}
     
        <footer style={{
          textAlign: 'center',
          padding: '10px',
          background: '#f7f7f750',
          color: '#000',
          height: 'auto',
          overflow: 'auto',
          zIndex: 1,
        }}>
          {/* Your footer content here */}
        </footer>
      </body>
    </html>
  );
}
